/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CharactersBigCard: typeof import('./components/learn/learnEndDialog/charactersBigLook/charactersBigCard.vue')['default']
    CharactersBigLook: typeof import('./components/learn/learnEndDialog/charactersBigLook.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LearnCard: typeof import('./components/learnCard.vue')['default']
    LearnEndDialog: typeof import('./components/learn/learnEndDialog.vue')['default']
    NameSlotDialog: typeof import('./components/nameSlotDialog.vue')['default']
    NameSlotDrawer: typeof import('./components/nameSlotDrawer.vue')['default']
    Navigation: typeof import('./components/topicBank/navigation.vue')['default']
    Part: typeof import('./components/topicBank/part.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCard: typeof import('./components/learn/selectCard.vue')['default']
    Unit: typeof import('./components/topicBank/unit.vue')['default']
  }
}
