/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CharactersBigCard: typeof import('./components/learn/learnEndDialog/charactersBigLook/charactersBigCard.vue')['default']
    CharactersBigLook: typeof import('./components/learn/learnEndDialog/charactersBigLook.vue')['default']
    CharactersBugCard: typeof import('./components/learn/learnEndDialog/charactersBugCard.vue')['default']
    CharactersCard: typeof import('./components/learn/learnEndDialog/charactersCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LearnCard: typeof import('./components/learnCard.vue')['default']
    LearnEndDialog: typeof import('./components/learn/learnEndDialog.vue')['default']
    NameSlotDialog: typeof import('./components/nameSlotDialog.vue')['default']
    NameSlotDrawer: typeof import('./components/nameSlotDrawer.vue')['default']
    Navigation: typeof import('./components/topicBank/navigation.vue')['default']
    Part: typeof import('./components/topicBank/part.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCard: typeof import('./components/learn/selectCard.vue')['default']
    Unit: typeof import('./components/topicBank/unit.vue')['default']
  }
}
